r1=Restaurant.create(name:"Atrea",email:"atrea@outlook.com",phno:1234567)
r2=Restaurant.create(name:"Olive Garden",email:"olivegd@outlook.com",phno:12345678)
r3=Restaurant.create(name:"Mini Punjab",email:"punjim@outlook.com",phno:923467892)
r4=Restaurant.create(name:"Delhi Darbar",email:"ddb@outlook.com",phno:41927865)


r1.menu_items.create(item_name:"Pizza",item_price:200)
r1.menu_items.create(item_name:"Margeritta-pizza",item_price:210)
r1.menu_items.create(item_name:"Burger",item_price:180)
r1.menu_items.create(item_name:"Pasta",item_price:200)
r1.menu_items.create(item_name:"Penne pasta",item_price:230)
r1.menu_items.create(item_name:"Fritatas",item_price:170)
r1.menu_items.create(item_name:"French-Toast",item_price:170)
r1.menu_items.create(item_name:"Sandwhiches",item_price:170)
r1.menu_items.create(item_name:"Kit-kat Shake",item_price:120)
r1.menu_items.create(item_name:"Kit-kat Boba",item_price:120)
r1.menu_items.create(item_name:"Oreo Shake",item_price:150)
r1.menu_items.create(item_name:"Orro Boba",item_price:150)
r1.menu_items.create(item_name:"Veg Club",item_price:250)
r1.menu_items.create(item_name:"Veg Noodles",item_price:200)
r1.menu_items.create(item_name:"Shezwan Noodles",item_price:200)
